version: "3"
services:
  my-db-container:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app-container:
    build:  .
    ports:
      - "8080:8080"
    depends_on:
      - my-db-container



